# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: 'windows-latest'

steps:
# Install .NET SDK
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '6.x'
    installationPath: $(Agent.ToolsDirectory)/dotnet

# Restore dependencies
- script: dotnet restore dotnetcoresample.csproj
  displayName: 'Restore dependencies'

# Build project
- script: dotnet build dotnetcoresample.csproj --configuration Release --no-restore
  displayName: 'Build the project'

# Run tests (only if you have a test project)
# If not, you can comment this step
#- script: dotnet test --configuration Release --no-build --verbosity normal
#  displayName: 'Run unit tests'

# Publish build output
- task: CopyFiles@2
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)/bin/Release'
    Contents: '**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
